export const ROUTES = {
  AUTH: {
    LOGIN: "/auth/login",
    SIGNUP: "/auth/signup",
    FORGOT_PASSWORD: "/auth/forgot-password",
    RESET_PASSWORD: "/auth/reset-password",
    VERIFY_OTP: "/auth/verify-otp",
  },
  APP: {
    DASHBOARD: "/app/dashboard",
    TASKS: "/app/tasks",
    TIME_TRACK: "/app/time-track",
    GOALS: "/app/goals",
    WEALTH: "/app/wealth",
    HEALTH: "/app/health",
    NOTES: "/app/notes",
    ASSISTANT: "/app/assistant",
    COMMUNICATION: "/app/communication",
    ANALYTICS: "/app/analytics",
    LIFE_SCORE: "/app/life-score",
    SETTINGS: "/app/settings",
  },
  PUBLIC: {
    HOME: "/",
    FEATURES: "/features",
    PRICING: "/pricing",
    PRODUCT: "/product",
    TERMS: "/terms",
    PRIVACY: "/privacy",
    // ABOUT: "/about",
    // CONTACT: "/contact",
  },
} as const;
