export type CountryOption = {
  code: string
  name: string
  currency: string
  timezone: string
}

/** ISO country code → local currency + primary IANA timezone. */
export const COUNTRIES: CountryOption[] = [
  { code: "AF", name: "Afghanistan", currency: "AFN", timezone: "Asia/Kabul" },
  { code: "AL", name: "Albania", currency: "ALL", timezone: "Europe/Tirane" },
  { code: "DZ", name: "Algeria", currency: "DZD", timezone: "Africa/Algiers" },
  { code: "AR", name: "Argentina", currency: "ARS", timezone: "America/Argentina/Buenos_Aires" },
  { code: "AM", name: "Armenia", currency: "AMD", timezone: "Asia/Yerevan" },
  { code: "AU", name: "Australia", currency: "AUD", timezone: "Australia/Sydney" },
  { code: "AT", name: "Austria", currency: "EUR", timezone: "Europe/Vienna" },
  { code: "AZ", name: "Azerbaijan", currency: "AZN", timezone: "Asia/Baku" },
  { code: "BH", name: "Bahrain", currency: "BHD", timezone: "Asia/Bahrain" },
  { code: "BD", name: "Bangladesh", currency: "BDT", timezone: "Asia/Dhaka" },
  { code: "BY", name: "Belarus", currency: "BYN", timezone: "Europe/Minsk" },
  { code: "BE", name: "Belgium", currency: "EUR", timezone: "Europe/Brussels" },
  { code: "BZ", name: "Belize", currency: "BZD", timezone: "America/Belize" },
  { code: "BO", name: "Bolivia", currency: "BOB", timezone: "America/La_Paz" },
  { code: "BA", name: "Bosnia and Herzegovina", currency: "BAM", timezone: "Europe/Sarajevo" },
  { code: "BW", name: "Botswana", currency: "BWP", timezone: "Africa/Gaborone" },
  { code: "BR", name: "Brazil", currency: "BRL", timezone: "America/Sao_Paulo" },
  { code: "BN", name: "Brunei", currency: "BND", timezone: "Asia/Brunei" },
  { code: "BG", name: "Bulgaria", currency: "BGN", timezone: "Europe/Sofia" },
  { code: "KH", name: "Cambodia", currency: "KHR", timezone: "Asia/Phnom_Penh" },
  { code: "CM", name: "Cameroon", currency: "XAF", timezone: "Africa/Douala" },
  { code: "CA", name: "Canada", currency: "CAD", timezone: "America/Toronto" },
  { code: "CL", name: "Chile", currency: "CLP", timezone: "America/Santiago" },
  { code: "CN", name: "China", currency: "CNY", timezone: "Asia/Shanghai" },
  { code: "CO", name: "Colombia", currency: "COP", timezone: "America/Bogota" },
  { code: "CR", name: "Costa Rica", currency: "CRC", timezone: "America/Costa_Rica" },
  { code: "HR", name: "Croatia", currency: "EUR", timezone: "Europe/Zagreb" },
  { code: "CU", name: "Cuba", currency: "CUP", timezone: "America/Havana" },
  { code: "CY", name: "Cyprus", currency: "EUR", timezone: "Asia/Nicosia" },
  { code: "CZ", name: "Czech Republic", currency: "CZK", timezone: "Europe/Prague" },
  { code: "DK", name: "Denmark", currency: "DKK", timezone: "Europe/Copenhagen" },
  { code: "DO", name: "Dominican Republic", currency: "DOP", timezone: "America/Santo_Domingo" },
  { code: "EC", name: "Ecuador", currency: "USD", timezone: "America/Guayaquil" },
  { code: "EG", name: "Egypt", currency: "EGP", timezone: "Africa/Cairo" },
  { code: "SV", name: "El Salvador", currency: "USD", timezone: "America/El_Salvador" },
  { code: "EE", name: "Estonia", currency: "EUR", timezone: "Europe/Tallinn" },
  { code: "ET", name: "Ethiopia", currency: "ETB", timezone: "Africa/Addis_Ababa" },
  { code: "FI", name: "Finland", currency: "EUR", timezone: "Europe/Helsinki" },
  { code: "FR", name: "France", currency: "EUR", timezone: "Europe/Paris" },
  { code: "GE", name: "Georgia", currency: "GEL", timezone: "Asia/Tbilisi" },
  { code: "DE", name: "Germany", currency: "EUR", timezone: "Europe/Berlin" },
  { code: "GH", name: "Ghana", currency: "GHS", timezone: "Africa/Accra" },
  { code: "GR", name: "Greece", currency: "EUR", timezone: "Europe/Athens" },
  { code: "GT", name: "Guatemala", currency: "GTQ", timezone: "America/Guatemala" },
  { code: "HN", name: "Honduras", currency: "HNL", timezone: "America/Tegucigalpa" },
  { code: "HK", name: "Hong Kong", currency: "HKD", timezone: "Asia/Hong_Kong" },
  { code: "HU", name: "Hungary", currency: "HUF", timezone: "Europe/Budapest" },
  { code: "IS", name: "Iceland", currency: "ISK", timezone: "Atlantic/Reykjavik" },
  { code: "IN", name: "India", currency: "INR", timezone: "Asia/Kolkata" },
  { code: "ID", name: "Indonesia", currency: "IDR", timezone: "Asia/Jakarta" },
  { code: "IR", name: "Iran", currency: "IRR", timezone: "Asia/Tehran" },
  { code: "IQ", name: "Iraq", currency: "IQD", timezone: "Asia/Baghdad" },
  { code: "IE", name: "Ireland", currency: "EUR", timezone: "Europe/Dublin" },
  { code: "IL", name: "Israel", currency: "ILS", timezone: "Asia/Jerusalem" },
  { code: "IT", name: "Italy", currency: "EUR", timezone: "Europe/Rome" },
  { code: "JM", name: "Jamaica", currency: "JMD", timezone: "America/Jamaica" },
  { code: "JP", name: "Japan", currency: "JPY", timezone: "Asia/Tokyo" },
  { code: "JO", name: "Jordan", currency: "JOD", timezone: "Asia/Amman" },
  { code: "KZ", name: "Kazakhstan", currency: "KZT", timezone: "Asia/Almaty" },
  { code: "KE", name: "Kenya", currency: "KES", timezone: "Africa/Nairobi" },
  { code: "KW", name: "Kuwait", currency: "KWD", timezone: "Asia/Kuwait" },
  { code: "LV", name: "Latvia", currency: "EUR", timezone: "Europe/Riga" },
  { code: "LB", name: "Lebanon", currency: "LBP", timezone: "Asia/Beirut" },
  { code: "LY", name: "Libya", currency: "LYD", timezone: "Africa/Tripoli" },
  { code: "LT", name: "Lithuania", currency: "EUR", timezone: "Europe/Vilnius" },
  { code: "LU", name: "Luxembourg", currency: "EUR", timezone: "Europe/Luxembourg" },
  { code: "MO", name: "Macao", currency: "MOP", timezone: "Asia/Macau" },
  { code: "MY", name: "Malaysia", currency: "MYR", timezone: "Asia/Kuala_Lumpur" },
  { code: "MV", name: "Maldives", currency: "MVR", timezone: "Indian/Maldives" },
  { code: "MT", name: "Malta", currency: "EUR", timezone: "Europe/Malta" },
  { code: "MX", name: "Mexico", currency: "MXN", timezone: "America/Mexico_City" },
  { code: "MD", name: "Moldova", currency: "MDL", timezone: "Europe/Chisinau" },
  { code: "MN", name: "Mongolia", currency: "MNT", timezone: "Asia/Ulaanbaatar" },
  { code: "MA", name: "Morocco", currency: "MAD", timezone: "Africa/Casablanca" },
  { code: "MZ", name: "Mozambique", currency: "MZN", timezone: "Africa/Maputo" },
  { code: "MM", name: "Myanmar", currency: "MMK", timezone: "Asia/Yangon" },
  { code: "NP", name: "Nepal", currency: "NPR", timezone: "Asia/Kathmandu" },
  { code: "NL", name: "Netherlands", currency: "EUR", timezone: "Europe/Amsterdam" },
  { code: "NZ", name: "New Zealand", currency: "NZD", timezone: "Pacific/Auckland" },
  { code: "NI", name: "Nicaragua", currency: "NIO", timezone: "America/Managua" },
  { code: "NG", name: "Nigeria", currency: "NGN", timezone: "Africa/Lagos" },
  { code: "MK", name: "North Macedonia", currency: "MKD", timezone: "Europe/Skopje" },
  { code: "NO", name: "Norway", currency: "NOK", timezone: "Europe/Oslo" },
  { code: "OM", name: "Oman", currency: "OMR", timezone: "Asia/Muscat" },
  { code: "PK", name: "Pakistan", currency: "PKR", timezone: "Asia/Karachi" },
  { code: "PA", name: "Panama", currency: "PAB", timezone: "America/Panama" },
  { code: "PY", name: "Paraguay", currency: "PYG", timezone: "America/Asuncion" },
  { code: "PE", name: "Peru", currency: "PEN", timezone: "America/Lima" },
  { code: "PH", name: "Philippines", currency: "PHP", timezone: "Asia/Manila" },
  { code: "PL", name: "Poland", currency: "PLN", timezone: "Europe/Warsaw" },
  { code: "PT", name: "Portugal", currency: "EUR", timezone: "Europe/Lisbon" },
  { code: "QA", name: "Qatar", currency: "QAR", timezone: "Asia/Qatar" },
  { code: "RO", name: "Romania", currency: "RON", timezone: "Europe/Bucharest" },
  { code: "RU", name: "Russia", currency: "RUB", timezone: "Europe/Moscow" },
  { code: "SA", name: "Saudi Arabia", currency: "SAR", timezone: "Asia/Riyadh" },
  { code: "RS", name: "Serbia", currency: "RSD", timezone: "Europe/Belgrade" },
  { code: "SG", name: "Singapore", currency: "SGD", timezone: "Asia/Singapore" },
  { code: "SK", name: "Slovakia", currency: "EUR", timezone: "Europe/Bratislava" },
  { code: "SI", name: "Slovenia", currency: "EUR", timezone: "Europe/Ljubljana" },
  { code: "ZA", name: "South Africa", currency: "ZAR", timezone: "Africa/Johannesburg" },
  { code: "KR", name: "South Korea", currency: "KRW", timezone: "Asia/Seoul" },
  { code: "ES", name: "Spain", currency: "EUR", timezone: "Europe/Madrid" },
  { code: "LK", name: "Sri Lanka", currency: "LKR", timezone: "Asia/Colombo" },
  { code: "SE", name: "Sweden", currency: "SEK", timezone: "Europe/Stockholm" },
  { code: "CH", name: "Switzerland", currency: "CHF", timezone: "Europe/Zurich" },
  { code: "SY", name: "Syria", currency: "SYP", timezone: "Asia/Damascus" },
  { code: "TW", name: "Taiwan", currency: "TWD", timezone: "Asia/Taipei" },
  { code: "TZ", name: "Tanzania", currency: "TZS", timezone: "Africa/Dar_es_Salaam" },
  { code: "TH", name: "Thailand", currency: "THB", timezone: "Asia/Bangkok" },
  { code: "TT", name: "Trinidad and Tobago", currency: "TTD", timezone: "America/Port_of_Spain" },
  { code: "TN", name: "Tunisia", currency: "TND", timezone: "Africa/Tunis" },
  { code: "TR", name: "Turkey", currency: "TRY", timezone: "Europe/Istanbul" },
  { code: "UG", name: "Uganda", currency: "UGX", timezone: "Africa/Kampala" },
  { code: "UA", name: "Ukraine", currency: "UAH", timezone: "Europe/Kyiv" },
  { code: "AE", name: "United Arab Emirates", currency: "AED", timezone: "Asia/Dubai" },
  { code: "GB", name: "United Kingdom", currency: "GBP", timezone: "Europe/London" },
  { code: "US", name: "United States", currency: "USD", timezone: "America/New_York" },
  { code: "UY", name: "Uruguay", currency: "UYU", timezone: "America/Montevideo" },
  { code: "UZ", name: "Uzbekistan", currency: "UZS", timezone: "Asia/Tashkent" },
  { code: "VE", name: "Venezuela", currency: "VES", timezone: "America/Caracas" },
  { code: "VN", name: "Vietnam", currency: "VND", timezone: "Asia/Ho_Chi_Minh" },
  { code: "YE", name: "Yemen", currency: "YER", timezone: "Asia/Aden" },
  { code: "ZM", name: "Zambia", currency: "ZMW", timezone: "Africa/Lusaka" },
  { code: "ZW", name: "Zimbabwe", currency: "ZWL", timezone: "Africa/Harare" },
]

export const TIMEZONES = [
  "Africa/Accra",
  "Africa/Addis_Ababa",
  "Africa/Algiers",
  "Africa/Cairo",
  "Africa/Casablanca",
  "Africa/Dar_es_Salaam",
  "Africa/Douala",
  "Africa/Gaborone",
  "Africa/Harare",
  "Africa/Johannesburg",
  "Africa/Kampala",
  "Africa/Lagos",
  "Africa/Lusaka",
  "Africa/Maputo",
  "Africa/Nairobi",
  "Africa/Tripoli",
  "Africa/Tunis",
  "America/Anchorage",
  "America/Argentina/Buenos_Aires",
  "America/Asuncion",
  "America/Belize",
  "America/Bogota",
  "America/Caracas",
  "America/Chicago",
  "America/Costa_Rica",
  "America/Denver",
  "America/Edmonton",
  "America/El_Salvador",
  "America/Guatemala",
  "America/Guayaquil",
  "America/Halifax",
  "America/Havana",
  "America/Jamaica",
  "America/La_Paz",
  "America/Lima",
  "America/Los_Angeles",
  "America/Managua",
  "America/Mexico_City",
  "America/Montevideo",
  "America/New_York",
  "America/Panama",
  "America/Phoenix",
  "America/Port_of_Spain",
  "America/Santiago",
  "America/Santo_Domingo",
  "America/Sao_Paulo",
  "America/Tegucigalpa",
  "America/Toronto",
  "America/Vancouver",
  "America/Winnipeg",
  "Asia/Aden",
  "Asia/Almaty",
  "Asia/Amman",
  "Asia/Baghdad",
  "Asia/Bahrain",
  "Asia/Baku",
  "Asia/Bangkok",
  "Asia/Beirut",
  "Asia/Brunei",
  "Asia/Colombo",
  "Asia/Damascus",
  "Asia/Dhaka",
  "Asia/Dubai",
  "Asia/Ho_Chi_Minh",
  "Asia/Hong_Kong",
  "Asia/Jakarta",
  "Asia/Jerusalem",
  "Asia/Kabul",
  "Asia/Karachi",
  "Asia/Kathmandu",
  "Asia/Kolkata",
  "Asia/Kuala_Lumpur",
  "Asia/Kuwait",
  "Asia/Macau",
  "Asia/Manila",
  "Asia/Muscat",
  "Asia/Nicosia",
  "Asia/Phnom_Penh",
  "Asia/Qatar",
  "Asia/Riyadh",
  "Asia/Seoul",
  "Asia/Shanghai",
  "Asia/Singapore",
  "Asia/Taipei",
  "Asia/Tashkent",
  "Asia/Tbilisi",
  "Asia/Tehran",
  "Asia/Tokyo",
  "Asia/Ulaanbaatar",
  "Asia/Yangon",
  "Asia/Yerevan",
  "Atlantic/Reykjavik",
  "Australia/Adelaide",
  "Australia/Brisbane",
  "Australia/Perth",
  "Australia/Sydney",
  "Europe/Amsterdam",
  "Europe/Athens",
  "Europe/Belgrade",
  "Europe/Berlin",
  "Europe/Bratislava",
  "Europe/Brussels",
  "Europe/Bucharest",
  "Europe/Budapest",
  "Europe/Chisinau",
  "Europe/Copenhagen",
  "Europe/Dublin",
  "Europe/Helsinki",
  "Europe/Istanbul",
  "Europe/Kyiv",
  "Europe/Lisbon",
  "Europe/Ljubljana",
  "Europe/London",
  "Europe/Luxembourg",
  "Europe/Madrid",
  "Europe/Malta",
  "Europe/Minsk",
  "Europe/Moscow",
  "Europe/Oslo",
  "Europe/Paris",
  "Europe/Prague",
  "Europe/Riga",
  "Europe/Rome",
  "Europe/Sarajevo",
  "Europe/Skopje",
  "Europe/Sofia",
  "Europe/Stockholm",
  "Europe/Tallinn",
  "Europe/Tirane",
  "Europe/Vienna",
  "Europe/Vilnius",
  "Europe/Warsaw",
  "Europe/Zagreb",
  "Europe/Zurich",
  "Indian/Maldives",
  "Pacific/Auckland",
  "Pacific/Honolulu",
  "UTC",
] as const

export type TimezoneValue = (typeof TIMEZONES)[number]

const COUNTRY_BY_CODE = new Map(COUNTRIES.map((country) => [country.code, country]))

export function getCountryByCode(code: string) {
  return COUNTRY_BY_CODE.get(code.toUpperCase())
}

export function getCurrencyForCountry(countryCode: string): string {
  return getCountryByCode(countryCode)?.currency ?? "USD"
}

export function getTimezoneForCountry(countryCode: string): string {
  return getCountryByCode(countryCode)?.timezone ?? "UTC"
}

export const COUNTRY_CODES = COUNTRIES.map((country) => country.code)
export const TIMEZONE_VALUES = [...TIMEZONES]
